version: "3.9"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway-container
    ports:
      - "8080:8080"
    networks:
      - e-commerce-platform

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "80:80"
    networks:
      - e-commerce-platform

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service-container
    ports:
      - "8082:8080"
    depends_on:
      - order-service-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-service-db:5432/${ORDER_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${ORDER_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${ORDER_DB_PASSWORD}
    networks:
      - e-commerce-platform

  payment-service:
    build:
      context: ./payment-service
      dockerfile: dockerfile
    container_name: payment-service-container
    ports:
      - "8083:8080"
    depends_on:
    - payment-service-db
    environment:
      ConnectionStrings__DefaultConnection: Server=payment-service-db;Port=3306;Database=${PAYMENT_DB_NAME};User=${PAYMENT_DB_USER};Password=${PAYMENT_DB_PASSWORD};
    networks:
      - e-commerce-platform

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service-container
    ports:
      - "8084:8080"
    depends_on:
      - product-service-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-service-db:5432/${PRODUCT_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${PRODUCT_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${PRODUCT_DB_PASSWORD}
    networks:
      - e-commerce-platform

  store-service:
    build:
      context: ./store-service
      dockerfile: Dockerfile
    container_name: store-service-container
    ports:
      - "8085:8080"
    depends_on:
      - store-service-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://store-service-db:5432/${STORE_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${STORE_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${STORE_DB_PASSWORD}
    networks:
      - e-commerce-platform

  user-service:
    build:
      context: ./user-service
      dockerfile: dockerfile
    container_name: user-service-container
    ports:
      - "8086:8080"
    depends_on:
      - user-service-db
    environment:
      ConnectionStrings__DefaultConnection: Server=user-service-db;Port=3306;Database=${USER_DB_NAME};User=${USER_DB_USER};Password=${USER_DB_PASSWORD};
    networks:
      - e-commerce-platform

  order-service-db:
    image: postgres:16
    container_name: order-service-db-container
    environment:
      POSTGRES_DB: ${ORDER_DB_NAME}
      POSTGRES_USER: ${ORDER_DB_USER}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - order-data:/var/lib/postgresql/data
    networks:
      - e-commerce-platform

  product-service-db:
    image: postgres:16
    container_name: product-service-db-container
    environment:
      POSTGRES_DB: ${PRODUCT_DB_NAME}
      POSTGRES_USER: ${PRODUCT_DB_USER}
      POSTGRES_PASSWORD: ${PRODUCT_DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - product-data:/var/lib/postgresql/data
    networks:
      - e-commerce-platform

  store-service-db:
    image: postgres:16
    container_name: store-service-db-container
    environment:
      POSTGRES_DB: ${STORE_DB_NAME}
      POSTGRES_USER: ${STORE_DB_USER}
      POSTGRES_PASSWORD: ${STORE_DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - store-data:/var/lib/postgresql/data
    networks:
      - e-commerce-platform

  user-service-db:
    image: mysql:8.0
    container_name: user-service-db-container
    restart: always
    environment:
      MYSQL_DATABASE: ${USER_DB_NAME}
      MYSQL_USER: ${USER_DB_USER}
      MYSQL_PASSWORD: ${USER_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${USER_DB_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - user-data:/var/lib/postgresql/data
    networks:
      - e-commerce-platform


  payment-service-db:
    image: mysql:8.0
    container_name: payment-service-db-ciontainer
    restart: always
    environment:
      MYSQL_DATABASE: ${PAYMENT_DB_NAME}
      MYSQL_USER: ${PAYMENT_DB_USER}
      MYSQL_PASSWORD: ${PAYMENT_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PAYMENT_DB_ROOT_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - payment-data:/var/lib/postgresql/data
    networks:
      - e-commerce-platform


volumes:
  order-data:
  product-data:
  store-data:
  user-data:
  payment-data:

networks:
  e-commerce-platform:
    name: e-commerce-platform