version: "3.9"

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway-container
    ports:
      - "8080:8080"
    networks:
      - e-commerce-platform

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "80:80"
    networks:
      - e-commerce-platform

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service-container
    ports:
      - "8082:8080"
    depends_on:
      - order-service-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order-service-db:5432/${ORDER_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${ORDER_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${ORDER_DB_PASSWORD}
    networks:
      - e-commerce-platform

  payment-service:
    build:
      context: ./payment-service
      dockerfile: dockerfile
    container_name: payment-service-container
    ports:
      - "8083:8080"
    networks:
      - e-commerce-platform

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service-container
    ports:
      - "8084:8080"
    depends_on:
      - product-service-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://product-service-db:5432/${PRODUCT_DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${PRODUCT_DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${PRODUCT_DB_PASSWORD}
    networks:
      - e-commerce-platform

  store-service:
    build:
      context: ./store-service
      dockerfile: Dockerfile
    container_name: store-service-container
    ports:
      - "8085:8080"
    networks:
      - e-commerce-platform

  user-service:
    build:
      context: ./user-service
      dockerfile: dockerfile
    container_name: user-service-container
    ports:
      - "8086:8080"
    networks:
      - e-commerce-platform

  order-service-db:
    image: postgres:16
    container_name: order-service-db-container
    environment:
      POSTGRES_DB: ${ORDER_DB_NAME}
      POSTGRES_USER: ${ORDER_DB_USER}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - order-data:/var/lib/postgresql/data
    networks:
      - e-commerce-platform

  product-service-db:
    image: postgres:16
    container_name: product-service-db-container
    environment:
      POSTGRES_DB: ${PRODUCT_DB_NAME}
      POSTGRES_USER: ${PRODUCT_DB_USER}
      POSTGRES_PASSWORD: ${PRODUCT_DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - product-data:/var/lib/postgresql/data
    networks:
      - e-commerce-platform


volumes:
  order-data:
  product-data:

networks:
  e-commerce-platform: