  name: CI Pipline

  on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]

  jobs:


    integration-test:
      name: Build & Test All Services with Docker Compose
      runs-on: ubuntu-latest
      env:
        ORDER_DB_NAME: ${{ secrets.ORDER_DB_NAME }}
        ORDER_DB_USER: ${{ secrets.ORDER_DB_USER }}
        ORDER_DB_PASSWORD: ${{ secrets.ORDER_DB_PASSWORD }}
        PRODUCT_DB_NAME: ${{ secrets.PRODUCT_DB_NAME }}
        PRODUCT_DB_USER: ${{ secrets.PRODUCT_DB_USER }}
        PRODUCT_DB_PASSWORD: ${{ secrets.PRODUCT_DB_PASSWORD }}
      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Build and start all services
          run: docker compose up -d --build

        - name: Wait for services to start
          run: |
            echo "Waiting for all services to start..."
            sleep 25

        - name: Test Frontend
          run: curl --fail http://localhost:80 || (docker logs $(docker ps -q --filter "name=frontend") && exit 1)

        - name: Test API Gateway
          run: curl --fail http://localhost:8080/actuator/health || (docker logs $(docker ps -q --filter "name=api-gateway-container") && exit 1)

        - name: Test Order Service
          run: curl --fail http://localhost:8082/actuator/health || (docker logs $(docker ps -q --filter "name=order-service-container") && exit 1)

        - name: Test Product Service
          run: curl --fail http://localhost:8084/actuator/health || (docker logs $(docker ps -q --filter "name=product-service-container") && exit 1)

        - name: Test Store Service
          run: curl --fail http://localhost:8085/actuator/health || (docker logs $(docker ps -q --filter "name=store-service-container") && exit 1)

        - name: Test Payment Service
          run: curl --fail http://localhost:8083/health || (docker logs $(docker ps -q --filter "name=payment-service-container") && exit 1)

        - name: Test User Service
          run: curl --fail http://localhost:8086/health || (docker logs $(docker ps -q --filter "name=user-service-container") && exit 1)

        - name: Shut down all services
          run: docker compose down
